### PR TITLE
Fix Enmity for newer versions (223+)

### PR DESCRIPTION
**Pull request by SerStars**
This fix works (i have asked multiple people to test it on the latest versions of Discord)
How and why can be found at https://discord.com/channels/950850315601711176/1205946622995865600/1242974995609550878 (thanks to Rosie)
i want that this gets reviewed before merging.

### CODE REVIEW

**Comment by byeoon** [comment]
LGTM

**Comment by marioparaschiv** [comment]
Why override the function prototype if you're setting the same value twice? With or without that code, the toString primitive would run the same function, defining toString on the function prototype with the same value should have no effect. 

Could you try without the defineProperty?

**Comment by SerStars** [comment]
> Have you tested on earlier versions < 223?

give me like ~5 mins

**Comment by SerStars** [comment]
> > Have you tested on earlier versions < 223?
> 
> give me like ~5 mins

Latest Enmity version (219.1 (56119)) works

**Comment by marioparaschiv** [comment]
That's good. 

> should i try it with older versions (which ones should i)?
No need, it should be working. We are just preventing toString being overriden - that shouldn't affect past versions.

**Comment by SerStars** [comment]
> That's good.
> 
> > should i try it with older versions (which ones should i)?
> 
> No need, it should be working. We are just preventing toString being overriden - that shouldn't affect past versions.

Alrighty!

**Comment by SerStars** [comment]
After the discussion in the server, i think its ready to publish? but we gotta notify the users on 223 that they wont be able go in the app cause it loads forever or notify them before publishing, any opinions?

**Comment by marioparaschiv** [comment]
This won't be merged until there is compatibility for every existing version that users may be using.

**Pull request merged**
